# Generated by Django 5.0.6 on 2024-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_attachmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
