# .github/workflows/update-helm-and-deploy.yaml
name: Update Helm Chart To Synch With ArgoCD

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ECR"]
    types:
      - completed

jobs:
  update-and-deploy:
    runs-on: build-x64
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Helm chart repository
        uses: actions/checkout@v3
        with:
          repository: 'zenith-arabia/charts.git'
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}

      - name: Print working directory
        run: pwd      

        

      - name: Read the variable from the file
        id: read_image_tag
        run: |
          IMAGE_TAG=$(cat /home/ubuntu/runner-artifacts/image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "The IMAGE_TAG is $IMAGE_TAG" 

      - name: Update values.yaml with the new image tag
        run: |
          cd dev
          sed -i "s/^appVersion:.*/appVersion: \"${{ env.IMAGE_TAG }}\"/" values-chatbot-django.yaml

      - name: Commit and push changes to the Helm chart repository
        run: |
          cd dev
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add values-chatbot-django.yaml
          git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
          git push